homalg-project/Toposes

PackageInfo.g
gap/DerivedMethods.gi
gap/Topos.gd
gap/Topos.gi

I add the property `IsElementaryTopos` and add a final derivation that applies for elementary toposes.

Elementary topos property

---

PackageInfo.g
gap/MethodRecord.gi

Fixes https://github.com/homalg-project/FinSetsForCAP/issues/42
~This also needs https://github.com/homalg-project/CAP_project/pull/509.~

Comply with https://github.com/homalg-project/CAP_project/pull/492

---

.github/workflows/Tests.yml
PackageInfo.g
gap/BraidedCartesianCategoriesDerivedMethods.gi
gap/BraidedCartesianCategoriesMethodRecord.gi
gap/BraidedCocartesianCategoriesDerivedMethods.gi
gap/BraidedCocartesianCategoriesMethodRecord.gi
gap/CartesianCategoriesDerivedMethods.gi
gap/CartesianCategoriesMethodRecord.gi
gap/CartesianClosedCategoriesDerivedMethods.gi
gap/CartesianClosedCategoriesMethodRecord.gi
gap/CocartesianCategoriesDerivedMethods.gi
gap/CocartesianCategoriesMethodRecord.gi
gap/CocartesianCoclosedCategoriesDerivedMethods.gi
gap/CocartesianCoclosedCategoriesMethodRecord.gi
gap/DerivedMethods.gi
gap/DistributiveCartesianCategoriesMethodRecord.gi
gap/DistributiveCocartesianCategoriesMethodRecord.gi
gap/MethodRecord.gi
gap/SymmetricCartesianCategoriesDerivedMethods.gi
gap/SymmetricCartesianClosedCategoriesDerivedMethods.gi
gap/SymmetricCocartesianCategoriesDerivedMethods.gi
gap/SymmetricCocartesianCoclosedCategoriesDerivedMethods.gi
gap/Topos.gi
release-gap-package

Note: Actually only a very small subset of the changes is really needed for being compatible with the CAP PR, but since MonoidalCategories is updated, I decided to also fully update Toposes.

Adjust to https://github.com/homalg-project/CAP_project/pull/649

---

makefile

If there is a PR 'Apply PackageJanitor to gh-pages', please merge both PRs together.

Apply PackageJanitor

---

gap/CocartesianCoclosedCategories.gd

This originated from https://github.com/homalg-project/CAP_project/pull/756.

Coexp(1,a) -> Coexp(a,1)

---

PackageInfo.g
gap/CartesianCategories.gd
gap/CartesianClosedCategoriesDoc.gd
gap/CocartesianCategories.gd
gap/CocartesianCoclosedCategoriesDoc.gd
gap/Topos.gd

Dualizes "IsCartesianCategory" to "IsCocartesianCategory". If I am correct, we have no notion of the opposite of `IsElementaryTopos`.

Adjust to https://github.com/homalg-project/CAP_project/pull/759

---

PackageInfo.g
gap/CocartesianCoclosedCategoriesMethodRecord.gi
gap/Tools.gi
tst/Opposite.tst

* IsomorphismFromInternalCoHomToCoDual
* IsomorphismFromCoDualToInternalCoHom
* IsomorphismFromObjectToInternalCoHomWithGivenInternalCoHom
* IsomorphismFromObjectToInternalCoHom
* IsomorphismFromInternalCoHomToObjectWithGivenInternalCoHom
* IsomorphismFromInternalCoHomToObject

fixed several dual operations for cocartesian coclosed categories

---

PackageInfo.g
gap/ToposDerivedMethods.gi

by adding missing category as first argument
in call to ClassifyingMorphismOfSubobjectWithGivenSubobjectClassifier
and missing test object in call to UniversalMorphismFromCoproduct

made code of TruthMorphismOfOrWithGivenObjects compilable

---

PackageInfo.g
gap/ToposDerivedMethods.gi
tst/Opposite.tst

AddDerivationToCAP for
* CartesianLeftUnitorWithGivenDirectProduct
* CartesianRightUnitorWithGivenDirectProduct
* CocartesianLeftUnitorInverseWithGivenCoproduct
* CocartesianRightUnitorInverseWithGivenCoproduct

installed derived methods for the (co)cartesian unitors

---

PackageInfo.g
gap/CartesianCategoriesProperties.gd
gap/CocartesianCategoriesProperties.gd
init.g

* IsCartesianCategory
* IsCocartesianCategory

updated two CAP_INTERNAL_CONSTRUCTIVE_CATEGORIES_RECORD entries

---

PackageInfo.g
tst/Opposite.tst

comply with CAP's merge-commit fadefbf5b8f3a2c5c41ae6245281752f58bf5957

comply with latest CAP

---

PackageInfo.g
doc/Doc.autodoc
gap/Topos.autogen.gd
gap/Topos.gd
gap/ToposDerivedMethods.gi
gap/ToposMethodRecord.gi
tst/Opposite.tst

and used it to simplify code of ListOfSubobjects

added new CAP operation MorphismsOfExternalHom

---

PackageInfo.g
examples/OppositeCategory.g
gap/Topos.gi
gap/ToposDerivedMethods.gi
tst/Opposite.tst

for IsCodistributiveCocartesianCategory

AddDerivationToCAP( Left/RightCocartesianCodistributivityFactoringWithGivenObjects, ... )

---

PackageInfo.g
gap/CartesianCategories.gd
gap/CartesianCategoriesProperties.gd
gap/CocartesianCategories.gd
gap/CocartesianCategoriesProperties.gd

from autogenerated C(oc)artesianCategories.gd to C(oc)artesianCategoriesProperties.gd

moved CAP_INTERNAL_CONSTRUCTIVE_CATEGORIES_RECORD.IsC(oc)artesianCategory

---

PackageInfo.g
gap/ToposDerivedMethods.gi

following discussion with @zickgraf, see
https://github.com/homalg-project/FinSetsForCAP/pull/109#pullrequestreview-989955149

reintroduced AddDerivationToCAP( MorphismsOfExternalHom, ... )

---

PackageInfo.g
examples/InitialCategory.g
gap/InitialCategory.gi

* AddIsEqualForObjects
* AddIsEqualForMorphisms
* AddIsCongruentForMorphisms
* AddIdentityMorphism
* AddPreCompose
following suggestion by @zickgraf:
see https://github.com/homalg-project/Toposes/pull/103#issuecomment-1158644380

added 5 operations to InitialCategory

---

PackageInfo.g
gap/ToposDerivedMethods.gi

Let the automated detection handle this.

Remove wrong precondition of a derivation

---

PackageInfo.g
gap/ToposDerivedMethods.gi

Also already prepare for automatically detecting those preconditions in the
future by introducing `CategoryGetters`.

Specify range category of homomorphism structure in preconditions of derivations

---

.codecov.yml
.github/workflows/Tests.yml
PackageInfo.g
README.md
ci_gaprc
doc/Doc.autodoc
gap/Topos.autogen.gd
gap/Topos.gd
gap/ToposMethodRecord.gi
makefile
process_coverage.py
tst/testall.g
upload_codecov.sh

outsourced from CategoryConstructor v2022.11-04

d&a ExactCoverWithGlobalElements

---

PackageInfo.g
gap/ToposDerivedMethods.gi

this is the SkeletalFinSets-analog of deriving the HomStructure from BasisOfExternalHom (and CoefficientsOfMorphism)
In our code CoefficientsOfMorphism corresponds to -1 + SafePosition

derive the HomStructure from MorphismsOfExternalHom

---

PackageInfo.g
gap/Topos.gd

from PR https://github.com/homalg-project/CAP_project/pull/1174

comply with CAP v2022.11-25

---

.github/workflows/Tests.yml
PackageInfo.g
tst/100_LoadPackage.tst
tst/Opposite.tst

This reverts commit aae7895f10fecd438804fe0266e5aace82c19ede.

partially Revert "got rid of suggested dependencies"

---

PackageInfo.g
examples/OppositeCategory.g
tst/Opposite.tst

from PR https://github.com/homalg-project/CAP_project/pull/1188

comply with CAP v2022.12-03

---

PackageInfo.g

needed for DigraphOfSubobjects in Tools.gi
another partial revert of aae7895f10fecd438804fe0266e5aace82c19ede

reintroduce suggested dependency on Digraphs

---

PackageInfo.g
tst/Opposite.tst

from PR https://github.com/homalg-project/CAP_project/pull/1227

comply with CartesianCategories v2023.01-01

---

PackageInfo.g
gap/ToposDerivedMethods.gi

in AddDerivationToCAP( HomomorphismStructureOnMorphismsWithGivenObjects, ... )

fixed call of UniversalMorphismFromCoproduct to support empty coproduct

---

PackageInfo.g
tst/Opposite.tst

from PR https://github.com/homalg-project/CAP_project/pull/1230

comply with CAP v2023.01-09
